const information = {
  'e1': 'zerre',
  'e2': 'omuz',
  'e3': 'aperture',
  'e4': 'çizgi kalınlığı',
  'e5': 'spur',
  'e6': 'eksen',
  'e7': 'omuz',
  'e8': 'çıkış',
  'e9': 'iniş',
  'e10': 'bitiş',
  'e11': 'köprü',
  'e12': 'bowl',
  'e13': 'terminal',
  'e14': 'terminal',
  'e15': 'ilmik',
  'e16': 'boyun',
  'e17': 'kulak',
  'e18': 'kuyruk',
  'e19': 'köprü',
  'e20': 'apex',
  'e21': 'vertex',
  'e22': 'overhang',
  'e23': 'tepe',
  'e24': 'tepe',
  'e25': 'gaga',
  'e26': 'joint',
  'e27': 'dirsek',
  'e28': 'dirsek',
  'e29': 'köprü',
  'e30': 'kemer',
  'e31': 'bilateral serif',
  'e32': 'bilateral serif',
  'e33': 'ayak',
  'e34': 'kapalı oda',
  'e35': 'hairline (stroke)',
  'e36': 'çatal',
  'e37': 'bacak',
  'e38': 'kol',
  'e39': 'bowl',
  'e40': 'eye',
  'e41': 'açık oda',
  'e42': 'kol',
  'e43': 'stress',
  'e44': 'tırnak',
  'e45': 'bağ',
  'e46': 'gaga',
  'e47': 'omurga',
  'e48': 'head serif',
  'e49': 'head serif'
}
